import { createSlice } from '@reduxjs/toolkit'; // Importing createSlice from Redux Toolkit

// Defining the initial state for the auth slice
const initialState = {
  isLoggedIn: false, // Initial state is not logged in
};

// Creating the auth slice
const authSlice = createSlice({
  name: 'auth', // Name of the slice
  initialState, // Initial state of the slice
  reducers: {
    // Reducer to handle login action
    login: (state) => {
      state.isLoggedIn = true; // Set isLoggedIn to true
    },
    // Reducer to handle logout action
    logout: (state) => {
      state.isLoggedIn = false; // Set isLoggedIn to false
    },
  },
});

// Exporting the actions generated by createSlice
export const { login, logout } = authSlice.actions;

// Exporting the reducer generated by createSlice as the default export
export default authSlice.reducer;